### ISSUE TITLE
Location attribute cannot be overridden

### ISSUE THREAD

**Issue by pavel-github** [cloudsigma/terraform-provider-cloudsigma#2]
### Description
Currently `location` attribute in `provider` section cannot be overridden to any values except `zrh`.

### How to reproduce
Set `location` to any value expect `zrh`. Run `terraform apply` to create resources, check in web UI that resources were created under `zrh` location.

### Example
```
variable "cloudsigma_username" {}
variable "cloudsigma_password" {}

provider "cloudsigma" {
  username = var.cloudsigma_username
  password = var.cloudsigma_password
  location = "fra"
}
```

**Comment by pavel-github** [comment]
Successfully tested for `gva` location.

**Comment by miguel-cs** [comment]
:+1:  thank you @pavel-github
