### ISSUE TITLE
Attaching multiple drives produces incorrect boot order

### ISSUE THREAD

**Issue by simonsparks** [cloudsigma/terraform-provider-cloudsigma#40]
# Bug report

### Description
When a server is provisioned with 2 drives attached, the boot order of those drives doesn't reflect the order in the terraform configuration. In fact, the first drive doesn't appear to have a boot order set at all and the second drive has a boot order of `1`.

This makes it difficult to configure a server with, for example, a bootable system drive and a secondary storage drive.

In the `resource_cloudsigma_server.go` file it appears that the boot order is determined from `len(serverDrives)` as drive definitions are being added to that list. Perhaps `serverDrives` is null until the first drive is added, causing `len(serverDrives)` to also be undefined (I'm not a Go expert)?

### Terraform Version
```
Terraform v1.1.4
+ provider.cloudsigma 1.10.0
```

### Affected Resource(s)
* cloudsigma_server

### Terraform Configuration Files
```hcl
data "cloudsigma_library_drive" "openbsd" {
  filter {
    name   = "name"
    values = ["OpenBSD 6.9 Server"]
  }
}

resource "cloudsigma_drive" "system" {
  media          = "disk"
  name           = "system"
  size           = 10 * 1024 * 1024 * 1024
  clone_drive_id = data.cloudsigma_library_drive.openbsd.id
}

resource "cloudsigma_drive" "storage" {
  media = "disk"
  name  = "storage"
  size  = 10 * 1024 * 1024 * 1024
}

resource "cloudsigma_ssh_key" "my_key" {
  name       = "my_key"
  public_key = file(var.my_ssh_key_path)
}

resource "cloudsigma_server" "my_server" {
  cpu          = 1 * 2 * 1000
  memory       = 1024 * 1024 * 1024
  name         = "my_server"
  vnc_password = var.my_vnc_password
  ssh_keys     = [cloudsigma_ssh_key.my_key.id]

  drive {
    uuid = cloudsigma_drive.system.id
  }

  drive {
    uuid = cloudsigma_drive.storage.id
  }
}
```

### Expected Behavior
It is expected that this configuration would provision a server with a `system` drive containing the operating system and a secondary `storage` drive, and that the `system` drive would come first in the boot order.

### Actual Behavior
The `system` drive has an undefined boot order and the `storage` drive has a boot order of `1`.
This causes the server to try and boot from the wrong drive.

### Steps to Reproduce
1. `terraform apply`
2. View the serial console via VNC. The displayed error shows that the server can't find a bootable drive.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by simonsparks** [comment]
The #41 PR does appear to solve my issue; the provisioned server has the 2 drives attached with appropriate boot ordering and it starts up correctly from the system drive.

**Comment by pavel-github** [comment]
@simonsparks , thanks for submitting the issue and PR.
How about we'll add an acceptance test to verify the correct behavior?

**Comment by simonsparks** [comment]
Hi @pavel-github, I'm not sure how to create the appropriate acceptance test for this behavior with your current test framework.
It look to me that the existing tests check the generated Terraform state to verify behavior, but in this case I don't think that boot order is included in that state. When I run a deployment, the resulting `cloudsigma_server` state just includes this for the attached drives:
```
{
  "mode": "managed",
  "type": "cloudsigma_server",
  "provider": "provider[\"registry.terraform.io/cloudsigma/cloudsigma\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "drive": [
          {
            "uuid": "6a1e2db2-7e41-4563-a2de-5e29140a65bf"
          },
          {
            "uuid": "486323e7-7bd4-432b-98f5-d6dac5e59d42"
          }
        ],
      ...
```

What we really need to verify is the boot order properties of those mounted drives:
![CloudSigma_Server_BootOrder](https://user-images.githubusercontent.com/1267754/162701821-aec793a7-47a9-45d4-8fcb-4acfc73c0a8d.png)

We can see these values from a GET request against the CloudSigma API:
`GET https://gva.cloudsigma.com/api/2.0/servers/detail`:
```
{
    "objects": [
        {
           ...
            "drives": [
                {
                    "boot_order": 1,
                    "dev_channel": "0:0",
                    "device": "virtio",
                    "drive": {
                        "resource_uri": "/api/2.0/drives/6a1e2db2-7e41-4563-a2de-5e29140a65bf/",
                        "uuid": "6a1e2db2-7e41-4563-a2de-5e29140a65bf"
                    },
                    ...
                },
                {
                    "boot_order": 2,
                    "dev_channel": "0:1",
                    "device": "virtio",
                    "drive": {
                        "resource_uri": "/api/2.0/drives/486323e7-7bd4-432b-98f5-d6dac5e59d42/",
                        "uuid": "486323e7-7bd4-432b-98f5-d6dac5e59d42"
                    },
                    ...
            ],
            ...
         }
      ]
}
```
but I don't think this will be available to your Terraform tests, will it?

**Comment by mjtrangoni** [comment]
Is there any reason why this "boot_order" is not exposed transparently as argument to the provider?
