### ISSUE TITLE
Change of Clone Drive in library leads to destroying and creating new disks

### ISSUE THREAD

**Issue by martin-huber** [cloudsigma/terraform-provider-cloudsigma#43]
# Bug report

### Description
In our terraform configuration we do a search for the uuid of the clone drive that should be used to create a new VM:
```hcl
data "cloudsigma_library_drive" "drive_library_ubuntu20" {
  filter {
    name   = "name"
    values = ["Ubuntu 20.04 LTS"]
  }
}
```
In the VM disk creation we refer to it:
```hcl
resource "cloudsigma_drive" "drive_testdrive" {
  media = "disk"
  name = "testdrive"
  size = 10 * module.const.GB
  clone_drive_id = module.lib.drive_library_ubuntu20
}
```

If now Cloudsigma uploads a new version of that Clone Drive that matches the name from the filter, a new UUID is returned and 
`terraform plan` thinks, that the property "clone_drive_id" of the disk did change locally, and reacts to that by having to destroy the existing disk and create a new one from that new Clone Drive.

This should not be done, a change in the Clone Drive only should be updated in the tf state, but not lead to any resource deletion.k

### Terraform Version
```
terraform -v
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/cloudsigma/cloudsigma v1.10.1

```

### Affected Resource(s)

* cloudsigma_drive

### Terraform Configuration Files
See on the top of the page.

### Expected Behavior
The local terraform state just should be updated with the new clone drive uuid

### Actual Behavior
Terraform detects change of clone_drive_id and thinks, this is a reason, that the disk needs to be destroyed and a new one has to be created.

### Steps to Reproduce
1. create a disk with some clone drive id
2. `terraform plan`
3.  `terraform apply`
4. change the clone drive id in the .tf file to another one
5. `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pavel-github** [comment]
👋 hey @martin-huber,
sorry for the late reply. We discussed internally how to address this issue and solve it in the Terraform-way (and we spoke with Terraform developers too).
So the canonical way to solve this would be using `lifecycle` hooks like this

```hcl
...
data "cloudsigma_library_drive" "drive_library_ubuntu20" {
  filter {
    name   = "name"
    values = ["Ubuntu 20.04 LTS"]
  }
}

resource "cloudsigma_drive" "drive_testdrive" {
  media = "disk"
  name = "testdrive"
  size = 10 * 1024 * 1024 * 1024
  clone_drive_id = data.cloudsigma_library_drive.drive_library_ubuntu20.id

  lifecycle {
    ignore_changes = [clone_drive_id]
  }
}
...
```

Internally the approach with matching filtered attribute and updating state file was not reliable and leads to other issues.
Let me know if this works for you or have other questions.

**Comment by pavel-github** [comment]
=> closing after inactivity.
