### ISSUE TITLE
Add missing `storage_type` field to cloudsigma_drive resource

### ISSUE THREAD

**Issue by mjtrangoni** [cloudsigma/terraform-provider-cloudsigma#49]
# Feature request

### Description

While creating a drive in **https://fra.cloudsigma.com** via terraform, it is always created with `storage_type` "nvme", which is BTW the more expensive one.  

[Cloudsigma Docs](https://github.com/cloudsigma/cloudsigma-docs/blob/master/drives.rst#storage-types) for storage types says that it is possible to define them via API while creating the drive, so it should be fine to add an optional field here.

### New or Affected Resource(s)

* cloudsigma_drive

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pavel-github** [comment]
@mjtrangoni, thanks for your input.
We'll take a look on it and will update the progress here.

**Comment by pavel-github** [comment]
merged with #60
