### ISSUE TITLE
Allow to add tags to servers and drives

### ISSUE THREAD

**Issue by martin-huber** [cloudsigma/terraform-provider-cloudsigma#6]
It already is great, that we now can create and mostly manage our Cloudsigma VMs with terraform.

There are a few features missing for us at the moment, that still require us to do a couple of manual steps in the Web-UI after VM creation.

One of these is: 
add a tag to the server and the drive, so we can add the VM and the drive to mark its category.

**Comment by pavel-github** [comment]
Hi @martin-huber , sounds like a valid use-case to me. I will update you when the new version with this feature is available.

**Comment by pavel-github** [comment]
Hey @martin-huber , 
🎉 our new version `v1.3.0` is released with a feature to add tags to server and drives. Here are documentation links with example snippets:

- https://registry.terraform.io/providers/cloudsigma/cloudsigma/latest/docs/resources/server#basic
- https://registry.terraform.io/providers/cloudsigma/cloudsigma/latest/docs/resources/drive#with-additional-tags

Let us know if it solve your use-case.

**Comment by martin-huber** [comment]
Hi @pavel-github  - that's great.
I tested and got an error:
`Error: PUT https://zrh.cloudsigma.com/api/2.0/drives/6e52d952-23a5-4dd8-b96c-dfece55f8caa/: 403 (request "09508bf7-de2a-4d6a-af69-00960f8fb789") [{Message:Cannot update a drive in state cloning_dst Point: Type:permission}]`

I guess, it is trying to update the drive and set the tag while it still is cloning ?

**Comment by martin-huber** [comment]
P.S: I then tried ommiting the tag for the drive and setting one to the VM only:
since it took quite some time I again ran into the timeout issues - and the tag also was not set to the VM. So it seems, the tag is set after successful VM creation, but as this is timing out, the tagging is skipped ?

**Comment by martin-huber** [comment]
and - last comment: every failed drive tagging left a created drive, without having the info in the terraform state.
Therefore removing the  server and the drive again from the tf config, only removed the last drive and the server, but not all the subsequently created drives.
There should be done something with the error handling

**Comment by pavel-github** [comment]
Is it the same terraform configuration you sent me last time (with VLAN)? If yes, I'm going to replicate it on my side and ping you back with results.

**Comment by martin-huber** [comment]
Yes, the same config,with VLAN. 
Thanks !

**Comment by pavel-github** [comment]
@martin-huber, our latest version [1.4.0](https://github.com/cloudsigma/terraform-provider-cloudsigma/releases/tag/v1.4.0) contains the bugfix for the issue (tagging drive correctly without error).
Let me know if you still experience the issue or I can close this GH ticket. Thanks.

**Comment by martin-huber** [comment]
Hi @pavel-github  - I today just created a new VM. Tagging of the disk worked, but the tag unfortunately was not assigned to the VM. It was the same tag (with the same uuid) that should have been added.

In the "cloudsigma_drive" resource definition I am using the same syntax as in the "cloudsigma_server" def.:
`  tags = [
    module.tag.tagname
  ]
`

and module.tag.tagname has the uuid of the tag

**Comment by pavel-github** [comment]
@martin-huber,
The issues was found and will be fixed in the next release (today), so you'll be able to test it on Monday, 17. May. We'll cover this use case with integration tests.
Thanks for reporting the issue.

**Comment by pavel-github** [comment]
@martin-huber , the fix is available in version [v1.4.1](https://github.com/cloudsigma/terraform-provider-cloudsigma/releases/tag/v1.4.1).

**Comment by pavel-github** [comment]
I'm going to close this issue. @martin-huber feel free to re-open it if you experience the same behaviour.
Thanks.
