### ISSUE TITLE
Allow to automatically create subscriptions for the created resources

### ISSUE THREAD

**Issue by martin-huber** [cloudsigma/terraform-provider-cloudsigma#7]
It already is great, that we now can create and mostly manage our Cloudsigma VMs with terraform.

There are a few features missing for us at the moment, that still require us to do a couple of manual steps in the Web-UI after VM creation.

One of these is: 
after creating a new VM or drive or changing the parameters of the VM, we still have to go to the Web UI to buy a subscription for the VM, if we know, that it will run longer (what is the case most of the time).

It would be cool, if for a server or a drive could be specified, that the resources for it should be covered by monthly subscriptions or yearly ones, and if these should be autorenewed.
If additional resources are required (after RAM or CPU update for example) this also could be covered by an additional subscription.
If the VM and the drive are destroyed, it would be cool if all associated subscriptions could expire after the actual period (setting autorenew to false)

**Comment by pavel-github** [comment]
Hi @martin-huber,
it's could be tricky how to handle subsriptions with terraform create/delete lifecycle. E.g. a user run `terraform create` -> subscription will be buyed, then `terraform delete` -> associated subscription will be expired and we don't have any UUID to track it. If the user repeate create/delete commands, he will buy with each run a new subscriptions.

We investigating internally how to handle this situations. I understood your use-case and will keep you up-to-date.

**Comment by pavel-github** [comment]
=> closing this one, after internal discussion with the team. Subscriptions can not be used with normal `apply/delete` TF lifecycle.
