### ISSUE TITLE
Add build for openbsd_amd64

### ISSUE THREAD

**Issue by eradman** [cloudsigma/terraform-provider-cloudsigma#8]
Can OpenBSD amd64 be added to the standard build?

This is the output of `terraform  init`

```
Error: Failed to install provider

Error while installing cloudsigma/cloudsigma v1.0.1: provider
registry.terraform.io/cloudsigma/cloudsigma 1.0.1 is not available for
openbsd_amd64
```

**Comment by pavel-github** [comment]
Hi @eradman, yes, we'll add it to the build matrix.

**Comment by pavel-github** [comment]
Version `v1.1.0` is released and contains openbsd binary: https://github.com/cloudsigma/terraform-provider-cloudsigma/releases/tag/v1.1.0
@eradman , can you try it and confirm that it works? Thanks.

**Comment by eradman** [comment]
Indeed, the cloudsigma TF  provider works on OpenBSD now. Many thanks!
